MEAT_MENU = {
    "Chicken": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 1.5, 
    },
    "Beef": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 2.5,
    },
    "Steak": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 3.0,
    },
    "Tenderloin": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 3.1,
    },
    "Sirloin": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 3.2,
    },
    "Flank": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 3.3,
    },
    "Shrimp": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 3.4,
    },
    "Crab": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 3.5,
    },
    "Lobster": {
        "ingredients": {
            "chicken": 1,
            "beef": 1,
            "steak": 1,
            "tenderloin": 1,
            "sirloin": 1,
            "flank": 1,
            "shrimp": 1,
            "crab": 1,
            "lobster": 1,
        },
        "cost": 3.6,
    },
}